### ISSUE TITLE
overlap with compas_cgal?

### ISSUE THREAD

**Issue by jf---** [petrasvestartas/compas_wood#9]
hi @petrasvestartas,

it seems that `compas_wood` overlaps quite a bit with `compas_cgal`?
specifically: `src/frontend/src/wood/include`

**Comment by petrasvestartas** [comment]
@jf--- yes, it started literally from compas_cgal package, gradually modifying it.
The history of it was quite interesting:
1) in the beginning, I had a c# project working in grasshopper, but I always wanted to learn how can I develop a project not dependent on Rhino. At the same time I wanted to learn few other things: C++, CMake and also develop within Compas.
2) then I rewritten the code using OpenNurbs and PInvoke for .NET
3) then I asked Tom how to bring my code to Compas, who suggested to take a look at compas_cgal which I very much inspired from and learn from it.
4) the issue with pybind11 were build times since precompiled headers could not be turned on, or any other parallel build, and it is really slow to debug C++ coding errors, unless you split the project into C++ and C++ Python binding. 
5) then I looked at nanobind which allows CMake builds and a very transparent binding procedure, with almost identical python and c++ code because it allows to expose C++ types directly in Python, so less overhead wrapping and simpler syntax. 
6) CGAL is used as a Kernel for data-types mostly, it could be rewritten using your own implementation points, vectors, planes and a few intersection methods. I kept using CGAL because I became familiar with it in other projects like Cockroach for pointcloud processing and support from the developers was quite nice especially for more heavier algorithms.
